### PR TITLE
Update GraphQLOverHTTP.md

### PR DESCRIPTION
**Pull request by sungam3r**
Fix relative links

### CODE REVIEW

**Comment by benjie** [comment]
Seems to work fine without that change; are you sure it will work with it?

https://graphql.github.io/graphql-over-http/draft/#sel-DAJJDLAACNAi4G

https://graphql.github.io/graphql-over-http/draft/#sec-Request

https://graphql.github.io/graphql-over-http/draft/#sec-Response

**Comment by sungam3r** [comment]
Try navigate from https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

**Comment by sungam3r** [comment]
By the way, compare this link with the first one from https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#body section. It navigates to graphql.github.io and works.

**Comment by benjie** [comment]
> By the way, compare this link with the first one from [https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#body](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md?rgh-link-date=2022-09-06T09%3A35%3A35Z#body) section. It navigates to graphql.github.io and works.

Oops; hardcoding the spec URL into the spec is not desired - thanks for the heads up: https://github.com/graphql/graphql-over-http/pull/226

**Comment by benjie** [comment]
> Try navigate from [https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md?rgh-link-date=2022-09-06T08%3A48%3A30Z)

Navigating inside GitHub is not important; what's important is that it works in the generated spec-md document at https://graphql.github.io/graphql-over-http/

The current behaviour is the same as used in the GraphQL Spec proper; e.g. look at the last link in this section:

https://github.com/graphql/graphql-spec/blob/main/spec/Section%206%20--%20Execution.md#executing-selection-sets

> Note: See [Handling Field Errors](https://github.com/graphql/graphql-spec/blob/main/spec/Section%206%20--%20Execution.md#sec-Handling-Field-Errors) for more about this behavior.

The above works in the GraphQL spec fine, but doesn't work in GitHub.

**Comment by benjie** [comment]
I'm going to close this as I believe that the current state is correct for spec-md.

**Pull request closed without merging**
